#!/bin/sh

cp -r ~/.config/ranger/ ~/.dotfiles/config/
cp -r ~/.config/nvim/init.lua ~/.dotfiles/config/nvim/init.lua
cp -r ~/.config/alacritty/ ~/.dotfiles/config/
cp -r ~/.config/kitty/ ~/.dotfiles/config/
cp -r ~/.config/mpv/mpv.conf ~/.dotfiles/config/mpv/mpv.conf
cp -r ~/.config/picom/ ~/.dotfiles/config/
cp -r ~/.config/i3/ ~/.dotfiles/config/
cp -r ~/.config/lf/ ~/.dotfiles/config/
cp -r ~/.config/rclone/excludes.txt ~/.dotfiles/config/rclone/
cp -r ~/.config/mpd/ ~/.dotfiles/config/
cp -r ~/.config/tmux/ ~/.dotfiles/config/
cp -r ~/.config/qutebrowser/config.py ~/.dotfiles/config/qutebrowser/

cp -r ~/.emacs.d/lisp/ ~/.dotfiles/lisp/

cp -r ~/.local/bin/lfub ~/.dotfiles/lfub

cp ~/.config/fish/config.fish ~/.dotfiles/
cp ~/.emacs.d/init.el ~/.dotfiles/
cp ~/.bashrc ~/.dotfiles/bashrc
cp ~/.vimrc ~/.dotfiles/vimrc

cp ~/.Xresources ~/.dotfiles/Xresources
